name: "Multi Serial Scanner"
slug: "multi_serial_scanner"
description: "Always-on multi-serial scanner that publishes to MQTT and ignores non-target devices"
version: "0.1.0"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
map:
  - share:rw
options:
  mqtt_broker: "mqtt://homeassistant:1883"
  mqtt_username: ""
  mqtt_password: ""
  scan_interval: 1.0
  include_patterns:
    - "/dev/ttyUSB*"
    - "/dev/ttyACM*"
  exclude_patterns:
    - "/dev/ttyS*"
    - "/dev/input*"
    - "/dev/hidraw*"
  enable_discovery: true
  discovery_prefix: "homeassistant"
  probe_command: ""
schema:
  mqtt_broker: str
  mqtt_username: str?
  mqtt_password: str?
  scan_interval: float
  include_patterns:
    - str
  exclude_patterns:
    - str
  enable_discovery: bool
  discovery_prefix: str
  probe_command: str?
