name: "Multi Serial Scanner"
slug: "multi_serial_scanner"
description: "Enhanced multi-serial scanner with device type detection, MQTT queuing, and two-way communication"
version: "0.2.0"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
map:
  - share:rw
options:
  mqtt_broker: "mqtt://homeassistant:1883"
  mqtt_username: ""
  mqtt_password: ""
  scan_interval: 1.0
  include_patterns:
    - "/dev/ttyUSB*"
    - "/dev/ttyACM*"
  exclude_patterns:
    - "/dev/ttyS*"
    - "/dev/input*"
    - "/dev/hidraw*"
  enable_discovery: true
  discovery_prefix: "homeassistant"
  probe_command: ""
  # Enhanced settings
  device_timeout: 30.0
  retry_attempts: 3
  retry_delay: 1.0
  message_queue_size: 100
  enable_device_detection: true
  identification_timeout: 5.0
schema:
  mqtt_broker: str
  mqtt_username: str?
  mqtt_password: str?
  scan_interval: float
  include_patterns:
    - str
  exclude_patterns:
    - str
  enable_discovery: bool
  discovery_prefix: str
  probe_command: str?
  # Enhanced schema
  device_timeout: float?
  retry_attempts: int?
  retry_delay: float?
  message_queue_size: int?
  enable_device_detection: bool?
  identification_timeout: float?
